Config = {}

Config.marketitems = {
    ["General"] = {
        { ["name"] = "Tosti", ["price"] = 2, ["amount"] = 50, ["image"] = "tosti.png", ["itemname"] = "tosti" },
        { ["name"] = "Lighter", ["price"] = 2, ["amount"] = 50, ["image"] = "lighter.png", ["itemname"] = "lighter" },
        { ["name"] = "Rolling Paper", ["price"] = 2, ["amount"] = 5000, ["image"] = "rolling_paper.png", ["itemname"] = "rolling_paper" },
    },
    ["Foods"] = {
        { ["name"] = "Sandwich", ["price"] = 2, ["amount"] = 50, ["image"] = "sandwich.png", ["itemname"] = "sandwich" },
        { ["name"] = "Egg Sandwich", ["price"] = 5, ["amount"] = 10, ["image"] = "eggsandwich.png", ["itemname"] = "eggsandwich" },
        { ["name"] = "Tuna Sandwich", ["price"] = 4, ["amount"] = 10, ["image"] = "tunasandwich.png", ["itemname"] = "tunasandwich" },
        { ["name"] = "Ham Sandwich", ["price"] = 4, ["amount"] = 10, ["image"] = "hamsandwich.png", ["itemname"] = "hamsandwich" },
        { ["name"] = "Meteorite", ["price"] = 25, ["amount"] = 10, ["image"] = "meteorite.png", ["itemname"] = "meteorite" },
        { ["name"] = "Ego Chaser", ["price"] = 2, ["amount"] = 10, ["image"] = "egochaser.png", ["itemname"] = "egochaser" },
        { ["name"] = "PSNQS", ["price"] = 1, ["amount"] = 10, ["image"] = "psnqs.png", ["itemname"] = "psnqs" },
    },
    ["Drinks"] = {
        { ["name"] = "Water Bottle", ["price"] = 2, ["amount"] = 50, ["image"] = "water_bottle.png", ["itemname"] = "water_bottle" },
        { ["name"] = "Kurka Kola", ["price"] = 2, ["amount"] = 50, ["image"] = "cocacola.png", ["itemname"] = "kurkakola" },
        { ["name"] = "Twerks Candy", ["price"] = 2, ["amount"] = 50, ["image"] = "twerks_candy.png", ["itemname"] = "twerks_candy" },
        { ["name"] = "Snikkel Candy", ["price"] = 2, ["amount"] = 50, ["image"] = "snikkel_candy.png", ["itemname"] = "snikkel_candy" },
        { ["name"] = "Beer", ["price"] = 7, ["amount"] = 50, ["image"] = "beer.png", ["itemname"] = "beer" },
        { ["name"] = "Whiskey", ["price"] = 10, ["amount"] = 50, ["image"] = "whiskey.png", ["itemname"] = "whiskey" },
        { ["name"] = "Vodka", ["price"] = 12, ["amount"] = 50, ["image"] = "vodka.png", ["itemname"] = "vodka" },
        { ["name"] = "Orangotang Juice", ["price"] = 2, ["amount"] = 20, ["image"] = "orangotang.png", ["itemname"] = "orangotang" },
        { ["name"] = "Sprunk Soda", ["price"] = 1.5, ["amount"] = 30, ["image"] = "sprunk.png", ["itemname"] = "sprunk" },
        { ["name"] = "Ecola Cola", ["price"] = 1.5, ["amount"] = 25, ["image"] = "ecola.png", ["itemname"] = "ecola" },
    },
    ["Others"] = {
        { ["name"] = "Bandage", ["price"] = 100, ["amount"] = 50, ["image"] = "bandage.png", ["itemname"] = "bandage" },
    },
}

Config.hardwareitems = {
    ["General"] = {
        { ["name"] = "Skateboard", ["price"] = 300, ["amount"] = 10, ["type"] = "item", ["image"] = "skateboard.png", ["itemname"] = "skateboard" },
        { ["name"] = "License plate", ["price"] = 1230, ["amount"] = 10, ["type"] = "item", ["image"] = "plate.png", ["itemname"] = "licenseplate" },
        { ["name"] = "RC Car", ["price"] = 230, ["amount"] = 50, ["type"] = "item", ["image"] = "rccar.png", ["itemname"] = "rccar" },
        { ["name"] = "Binoculars", ["price"] = 50, ["amount"] = 50, ["type"] = "item", ["image"] = "binoculars.png", ["itemname"] = "binoculars" },
        { ["name"] = "Firework 1", ["price"] = 50, ["amount"] = 50, ["type"] = "item", ["image"] = "firework1.png", ["itemname"] = "firework1" },
        { ["name"] = "Firework 2", ["price"] = 50, ["amount"] = 50, ["type"] = "item", ["image"] = "firework2.png", ["itemname"] = "firework2" },
        { ["name"] = "Firework 3", ["price"] = 50, ["amount"] = 50, ["type"] = "item", ["image"] = "firework3.png", ["itemname"] = "firework3" },
        { ["name"] = "Firework 4", ["price"] = 50, ["amount"] = 50, ["type"] = "item", ["image"] = "firework4.png", ["itemname"] = "firework4" },
        { ["name"] = "Cleaning Kit", ["price"] = 150, ["amount"] = 150, ["type"] = "item", ["image"] = "cleaningkit.png", ["itemname"] = "cleaningkit" },
        { ["name"] = "Advanced Repair Kit", ["price"] = 500, ["amount"] = 50, ["type"] = "item", ["image"] = "advancedrepairkit.png", ["itemname"] = "advancedrepairkit" },
        { ["name"] = "Lockpick", ["price"] = 200, ["amount"] = 50, ["type"] = "item", ["image"] = "lockpick.png", ["itemname"] = "lockpick" },
        { ["name"] = "Weapon Wrench", ["price"] = 250, ["amount"] = 250, ["type"] = "item", ["image"] = "weapon_wrench.png", ["itemname"] = "weapon_wrench" },
        { ["name"] = "Weapon Hammer", ["price"] = 250, ["amount"] = 250, ["type"] = "item", ["image"] = "weapon_hammer.png", ["itemname"] = "weapon_hammer" },
        { ["name"] = "Notebook", ["price"] = 10, ["amount"] = 250, ["type"] = "item", ["image"] = "notebook.png", ["itemname"] = "notebook" },

    },
    ["Surveillance"] = {
        { ["name"] = "Camviewer", ["price"] = 729, ["amount"] = 150, ["type"] = "item", ["image"] = "camviewer.png", ["itemname"] = "camviewer" },
        { ["name"] = "360 CCTV", ["price"] = 496, ["amount"] = 150, ["type"] = "item", ["image"] = "mcctv.png", ["itemname"] = "360cctv" },
        { ["name"] = "CCTV", ["price"] = 250, ["amount"] = 150, ["type"] = "item", ["image"] = "nmcctv.png", ["itemname"] = "cctv" },
    },
    ["Communication"] = {
        { ["name"] = "Phone", ["price"] = 850, ["amount"] = 50, ["type"] = "item", ["image"] = "phone.png", ["itemname"] = "phone" },
        { ["name"] = "Radio", ["price"] = 250, ["amount"] = 50, ["type"] = "item", ["image"] = "radio.png", ["itemname"] = "radio" },
    },
    ["Drones"] = {
        { ["name"] = "B Drone", ["price"] = 399, ["amount"] = 1, ["type"] = "item", ["image"] = "drones.png", ["itemname"] = "bdrone" },
        { ["name"] = "Bad Drone", ["price"] = 499, ["amount"] = 1, ["type"] = "item", ["image"] = "drones.png", ["itemname"] = "baddrone" },
        { ["name"] = "BB Drone", ["price"] = 599, ["amount"] = 5, ["type"] = "item", ["image"] = "drones.png", ["itemname"] = "bbdrone" },
        { ["name"] = "BC Drone", ["price"] = 699, ["amount"] = 5, ["type"] = "item", ["image"] = "drones.png", ["itemname"] = "bcdrone" },
        { ["name"] = "BD Drone", ["price"] = 756, ["amount"] = 2, ["type"] = "item", ["image"] = "drones.png", ["itemname"] = "bddrone" },
    },
}

Config.weaponshopitems = {
    ["General"] = {
        { ["name"] = "Weapon Knife", ["price"] = 230, ["amount"] = 50, ["type"] = "item", ["image"] = "weapon_knife.png", ["itemname"] = "weapon_knife" },
        { ["name"] = "Weapon Bat", ["price"] = 250, ["amount"] = 250, ["type"] = "item", ["image"] = "weapon_bat.png", ["itemname"] = "weapon_bat" },
        { ["name"] = "Weapon Hatchet", ["price"] = 250, ["amount"] = 250, ["type"] = "item", ["image"] = "weapon_hatchet.png", ["itemname"] = "weapon_hatchet" },
    },
    ["Firearms"] = {
        { ["name"] = "Weapon Pistol", ["price"] = 2500, ["amount"] = 5, ["type"] = "item", ["image"] = "weapon_pistol.png", ["itemname"] = "weapon_pistol" },
        { ["name"] = "Weapon SNS Pistol", ["price"] = 1500, ["amount"] = 5, ["type"] = "item", ["image"] = "weapon_snspistol.png", ["itemname"] = "weapon_snspistol" },
        { ["name"] = "Weapon Vintage Pistol", ["price"] = 4000, ["amount"] = 5, ["type"] = "item", ["image"] = "weapon_vintagepistol.png", ["itemname"] = "weapon_vintagepistol" },
    },
    ["Ammunition"] = {
        { ["name"] = "Pistol Ammo", ["price"] = 250, ["amount"] = 250, ["type"] = "item", ["image"] = "pistol_ammo.png", ["itemname"] = "pistol_ammo" },
    },
}

Config.weedshopitems = {
    ["General"] = {
        { ["name"] = "Joint", ["price"] = 10, ["amount"] = 50, ["type"] = "item", ["image"] = "joint.png", ["itemname"] = "joint" },
        { ["name"] = "Weapon poolcue", ["price"] = 100, ["amount"] = 50, ["type"] = "item", ["image"] = "weapon_poolcue.png", ["itemname"] = "weapon_poolcue" },
        { ["name"] = "Weed nutrition", ["price"] = 20, ["amount"] = 50, ["type"] = "item", ["image"] = "weed_nutrition.png", ["itemname"] = "weed_nutrition" },
        { ["name"] = "Empty weed bag", ["price"] = 2, ["amount"] = 1000, ["type"] = "item", ["image"] = "empty_weed_bag.png", ["itemname"] = "empty_weed_bag" },
        { ["name"] = "Rolling Paper", ["price"] = 2, ["amount"] = 1000, ["type"] = "item", ["image"] = "rolling_paper.png", ["itemname"] = "rolling_paper" },
    },
    ["Weed"] = {
        { ["name"] = "fertilizer", ["price"] = 10, ["amount"] = 200, ["type"] = "item", ["image"] = "fertilizer.png", ["itemname"] = "fertilizer" },
        { ["name"] = "dust", ["price"] = 5, ["amount"] = 200, ["type"] = "item", ["image"] = "dust.png", ["itemname"] = "dust" },
        { ["name"] = "weed_seed", ["price"] = 15, ["amount"] = 200, ["type"] = "item", ["image"] = "weed_seed.png", ["itemname"] = "weed_seed" },
        { ["name"] = "water", ["price"] = 2, ["amount"] = 200, ["type"] = "item", ["image"] = "water.png", ["itemname"] = "water" },
    },
}


Config.Locations = {
    [1] = {
        ["name"] = "24/7 Supermarket",
        ["category"] = "24/7 Supermarket",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["radius"] = 1.5,
        ["coords"] = vector4(29.6401, -1343.4196, 29.4972, 183.9198),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },   
    [2] = {
        ["name"] = "24/7 Supermarket",
        ["category"] = "24/7 Supermarket",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["coords"] = vector4(-3039.54, 584.38, 7.91, 17.27),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },   
    [3] = {
        ["name"] = "24/7 Supermarket",
        ["category"] = "24/7 Supermarket",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["coords"] = vector4(-3245.5630, 1005.1959, 12.8309, 274.8986),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },   
    [4] = {
        ["name"] = "24/7 Supermarket",
        ["category"] = "24/7 Supermarket",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["coords"] = vector4(1734.2230, 6416.4268, 35.0374, 151.2908),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },   
    [5] = {
        ["name"] = "24/7 Supermarket",
        ["category"] = "24/7 Supermarket",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["coords"] = vector4(1962.4385, 3745.7163, 32.3439, 218.3884),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },   
    [6] = {
        ["name"] = "24/7 Supermarket",
        ["category"] = "24/7 Supermarket",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["coords"] = vector4(544.8484, 2666.9897, 42.1567, 10.5912),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },   
    [7] = {
        ["name"] = "24/7 Supermarket",
        ["category"] = "24/7 Supermarket",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["coords"] = vector4(2677.0576, 3285.1807, 55.2413, 261.8481),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },   
    [8] = {
        ["name"] = "24/7 Supermarket",
        ["category"] = "24/7 Supermarket",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["coords"] = vector4(2553.6982, 386.0314, 108.6231, 267.2679),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },  
    [9] = {
        ["name"] = "24/7 Supermarket",
        ["category"] = "24/7 Supermarket",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["coords"] = vector4(378.4329, 328.7618, 103.5665, 156.6076),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },    

    [10] = {
        ["name"] = "Hardware",
        ["category"] = "Hardware",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["radius"] = 1.5,
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["coords"] = vector4(45.68, -1749.04, 29.61, 53.13),
        ["categoryList"] = {
            ["General"] = "Security and maintenance.",
            ["Surveillance"] = "Surveillance cameras and equipment.",
            ["Communication"] = "Phones and radios for communication.",
            ["Drones"] = "Various types of drones.",
        --    ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.hardwareitems,
    },
    [11] = {
        ["name"] = "Hardware",
        ["category"] = "Hardware",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["coords"] = vector4(2747.71, 3472.85, 55.67, 255.08),
        ["categoryList"] = {
            ["General"] = "Security and maintenance.",
            ["Surveillance"] = "Surveillance cameras and equipment.",
            ["Communication"] = "Phones and radios for communication.",
            ["Drones"] = "Various types of drones.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.hardwareitems,
    },
    [12] = {
        ["name"] = "Hardware",
        ["category"] = "Hardware",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["coords"] = vector4(-421.83, 6136.13, 31.88, 228.2),
        ["categoryList"] = {
            ["General"] = "Security and maintenance.",
            ["Surveillance"] = "Surveillance cameras and equipment.",
            ["Communication"] = "Phones and radios for communication.",
            ["Drones"] = "Various types of drones.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.hardwareitems,
    },

    [13] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(-661.96, -933.53, 21.83, 177.05),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },

    [14] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(809.68, -2159.13, 29.62, 1.43),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [15] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(1692.67, 3761.38, 34.71, 227.65),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [16] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(-331.23, 6085.37, 31.45, 228.02),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [17] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(253.63, -51.02, 69.94, 72.91),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [18] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(23.0, -1105.67, 29.8, 162.91),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [19] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(2567.48, 292.59, 108.73, 349.68),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [20] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(-1118.59, 2700.05, 18.55, 221.89),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [21] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(841.92, -1035.32, 28.19, 1.56),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [22] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(-1304.19, -395.12, 36.7, 75.03),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [23] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(-3173.31, 1088.85, 20.84, 244.18),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [24] = {
        ["name"] = "LTD Gasoline",
        ["category"] = "LTD",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["coords"] = vector4(-47.02, -1758.23, 29.42, 45.05),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },       
    [25] = {
        ["name"] = "LTD Gasoline",
        ["category"] = "LTD",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["coords"] = vector4(-706.06, -913.97, 19.22, 88.04),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },    
    [26] = {
        ["name"] = "LTD Gasoline",
        ["category"] = "LTD",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["coords"] = vector4(-1820.02, 794.03, 138.09, 135.45),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },  
    [27] = {
        ["name"] = "LTD Gasoline",
        ["category"] = "LTD",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["coords"] = vector4(1164.71, -322.94, 69.21, 101.72),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },
    [28] = {
        ["name"] = "LTD Gasoline",
        ["category"] = "LTD",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["coords"] = vector4(1697.87, 4922.96, 42.06, 324.71),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },
    [29] = {
        ["name"] = "Smoke On The Water",
        ["category"] = "Enjoy :)",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 140,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["ped"] = 'a_m_y_hippy_01',
        ["scenario"] = "WORLD_HUMAN_AA_SMOKE",
        ["radius"] = 1.5,
        ["coords"] = vector4(-1168.26, -1573.2, 4.66, 105.24),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Weed"] = "Weed shop items.",
        },
        ["itemList"] = Config.weedshopitems,
    },    
}

Config.Framework = "QBCore" -- QBCore or ESX or OLDQBCore -- NewESX

function Config.Error(cb)
    if Config.Framework == "ESX"  then
        TriggerClientEvent('esx:showNotification', source, 'You do not have sufficient funds.')
    elseif Config.Framework == "NewESX" then
        TriggerClientEvent('esx:showNotification', source, 'You do not have sufficient funds.')
    elseif Config.Framework == "QBCore" then
        TriggerClientEvent('QBCore:Notify', source, 'You do not have sufficient funds.', 'error', 5000)
    elseif Config.Framework == "OLDQBCore" then
        TriggerClientEvent('QBCore:Notify', source, 'You do not have sufficient funds.', 'error', 5000)
    else
        print(Config.Framework)
        print("Error: Unrecognized framework selected.")
    end
end

function Config.Success()
    if Config.Framework == "ESX"then
        TriggerClientEvent('esx:showNotification', source, 'Purchase transConfigtion successful.', 'success')
    elseif Config.Framework == "NewESX" then 
        TriggerClientEvent('esx:showNotification', source, 'Purchase transConfigtion successful.', 'success')
    elseif Config.Framework == "QBCore" then
        TriggerClientEvent('QBCore:Notify', source, 'Purchase transConfigtion successful.', 'success', 5000)
    elseif  Config.Framework == "OLDQBCore" then
        TriggerClientEvent('QBCore:Notify', source, 'Purchase transConfigtion successful.', 'success', 5000)
    else
        print(Config.Framework)
        print("Error: Unrecognized framework selected.")
    end
end
